Update requests to newer version
Using requests~=2.24.0 causes urllib3 to be downgraded to urllib3
1.25.11.  Subsequently, attempts to import urllib3 fail with:

    ModuleNotFoundError: No module named 'urllib3.packages.six.moves'